name: Deploy Backend and Frontend

on:
  push:
    branches:
      - main

jobs:
  # Job to deploy the backend
  deploy_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH="$HOME/.fly/bin:$PATH"

      - name: Deploy Backend to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP_NAME: ${{ secrets.FLY_BACKEND_APP_NAME }}
        run: |
          flyctl deploy --app $FLY_APP_NAME --remote-only

  # Job to deploy the frontend
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH="$HOME/.fly/bin:$PATH"

      - name: Deploy Frontend to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP_NAME: ${{ secrets.FLY_FRONTEND_APP_NAME }}
        run: |
          flyctl deploy --app $FLY_APP_NAME --remote-only
